name: Update Emojis

on:
    workflow_dispatch:
    schedule:
        - cron: "0,15,30,45 * * * *" # Runs at 0, 15, 30, and 45 minutes past the hour.

jobs:
    update:
        name: update-all-emojis
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install
              run: npm install

            - name: Update Emojis
              run: npm run update

            - name: Commit Changes
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add .
                git commit -m 'Update Emojis'
                git push
